version : '4'

services: 
  opi-node-pg:
    image: bitnami/postgresql:latest 
    ports:
      -5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apinode